### ISSUE TITLE
php 8

### ISSUE THREAD

**Issue by ggm-dev** [magesuite/multiple-flat-shipping#1]
Hey all - 

Any plans to make this module compliant with 2.4.4 and php8?  

Thanks!

**Comment by diwipl** [comment]
Hi
Yes, we are internally working on Magento 2.4.5 update along with PHP 8 compatibility at the moment. 

During the updates of our internal projects, we want to make all extensions compatible with PHP 8.

ETA for specific modules cannot be specified tho.

**Comment by ggm-dev** [comment]
Looks like this has been updated.  

Thanks!
